### PR TITLE
English: Mage

### PR DESCRIPTION
**Pull request by brandonjpierce**
Added some additional comments to help organize the soundpaths file a bit more for us

### CODE REVIEW

**Comment by brandonjpierce** [comment]
Updated labels to shorten just slightly as they were getting cut off pretty aggressively. Using format of `TTS > Lang > Spell` but happy to play around with this even more.

**Comment by belsrc** [comment]
Would you rather go `TTS > Lang > Spel`,  `TTS : Lang : Spell`? Personally, all the same to me

**Comment by belsrc** [comment]
Also, before we start getting more files. Think we should start some sort of class based or lang based folder structure in the sound folder? Since I plan on adding English and Japanese for lock as well. Maybe not completely relevant in this PR, again, a general structure talking point.

**Comment by brandonjpierce** [comment]
Re: folder structure, I was actually going to suggest the same thing so I am +1 to that idea! Maybe something like:

```
sounds/
  english/
    mage/
    warlock/
  german/
    mage/
    warlock/
  japanese/
    mage/
    warlock/
```

Re: labels, indifferent as well, we could even tighten it up further with a lang abbreviation e.g. `TTS : EN : Spell`

**Comment by belsrc** [comment]
Cool, I'm good with both the folder structure and the `TTS : Abbr_Lang : Spell` as well. Want to change the text in this PR and I'll get the folder structure. Have the English and Japanese Lock ones ready to go on my end so can change it with them.

**Comment by brandonjpierce** [comment]
Sounds good i'll update this PR later today then!

**Comment by belsrc** [comment]
Guess that also means that we can change the file names themselves (In my PR), huh? Since they will already be in `lang -> class` folder, we can just name them `spell` going forward.

**Comment by belsrc** [comment]
Was looking for a lang abbreviation list and noticed, while its not the normal standard ones, there is a common 3-letter code that I think might work better for those that may or may-not be in this code/standards world.

Eng | Ger | Jpn

instead of

EN | DE | JA

thoughts?

**Comment by brandonjpierce** [comment]
Works for me!

**Review by belsrc — APPROVED** [review]
solid

**Pull request merged**
